
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

import absyn.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\112\000\002\002\004\000\002\015\003\000\002\043" +
    "\004\000\002\043\003\000\002\003\003\000\002\003\003" +
    "\000\002\002\005\000\002\002\010\000\002\040\003\000" +
    "\002\040\003\000\002\040\003\000\002\004\010\000\002" +
    "\030\010\000\002\031\003\000\002\031\003\000\002\041" +
    "\005\000\002\041\003\000\002\036\004\000\002\036\006" +
    "\000\002\010\006\000\002\042\004\000\002\042\002\000" +
    "\002\037\004\000\002\037\002\000\002\005\003\000\002" +
    "\005\003\000\002\005\003\000\002\005\003\000\002\005" +
    "\003\000\002\011\004\000\002\011\003\000\002\006\005" +
    "\000\002\006\003\000\002\012\007\000\002\012\011\000" +
    "\002\013\007\000\002\014\005\000\002\014\004\000\002" +
    "\035\003\000\002\035\006\000\002\016\005\000\002\016" +
    "\003\000\002\033\003\000\002\033\003\000\002\033\003" +
    "\000\002\033\003\000\002\033\003\000\002\033\003\000" +
    "\002\017\005\000\002\017\003\000\002\025\004\000\002" +
    "\025\003\000\002\020\005\000\002\020\003\000\002\007" +
    "\005\000\002\007\003\000\002\032\003\000\002\032\003" +
    "\000\002\021\005\000\002\021\003\000\002\034\003\000" +
    "\002\034\003\000\002\022\004\000\002\022\003\000\002" +
    "\023\005\000\002\023\003\000\002\023\003\000\002\023" +
    "\003\000\002\023\003\000\002\024\006\000\002\026\003" +
    "\000\002\026\002\000\002\027\005\000\002\027\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\165\000\010\004\005\007\004\011\007\001\002\000" +
    "\004\044\ufff9\001\002\000\004\044\ufff7\001\002\000\012" +
    "\002\ufffe\004\ufffe\007\ufffe\011\ufffe\001\002\000\004\044" +
    "\ufff8\001\002\000\004\002\167\001\002\000\012\002\000" +
    "\004\005\007\004\011\007\001\002\000\012\002\ufffc\004" +
    "\ufffc\007\ufffc\011\ufffc\001\002\000\004\044\015\001\002" +
    "\000\012\002\ufffd\004\ufffd\007\ufffd\011\ufffd\001\002\000" +
    "\010\034\016\035\020\037\017\001\002\000\040\002\ufffb" +
    "\004\ufffb\006\ufffb\007\ufffb\010\ufffb\011\ufffb\012\ufffb\015" +
    "\ufffb\030\ufffb\034\ufffb\035\ufffb\041\ufffb\042\ufffb\044\ufffb" +
    "\045\ufffb\001\002\000\004\045\163\001\002\000\010\004" +
    "\005\007\004\011\023\001\002\000\006\036\ufff4\043\161" +
    "\001\002\000\006\036\ufff1\043\ufff1\001\002\000\006\036" +
    "\ufff3\044\ufff8\001\002\000\004\044\156\001\002\000\004" +
    "\036\026\001\002\000\004\041\030\001\002\000\012\002" +
    "\ufff6\004\ufff6\007\ufff6\011\ufff6\001\002\000\036\004\uffec" +
    "\006\uffec\007\uffec\010\uffec\011\uffec\012\uffec\015\uffec\030" +
    "\uffec\034\uffec\035\uffec\041\uffec\042\uffec\044\uffec\045\uffec" +
    "\001\002\000\036\004\005\006\uffea\007\004\010\uffea\011" +
    "\007\012\uffea\015\uffea\030\uffea\034\uffea\035\uffea\041\uffea" +
    "\042\uffea\044\uffea\045\uffea\001\002\000\030\006\046\010" +
    "\044\012\040\015\037\030\053\034\041\035\050\041\030" +
    "\042\043\044\051\045\052\001\002\000\036\004\uffed\006" +
    "\uffed\007\uffed\010\uffed\011\uffed\012\uffed\015\uffed\030\uffed" +
    "\034\uffed\035\uffed\041\uffed\042\uffed\044\uffed\045\uffed\001" +
    "\002\000\004\044\035\001\002\000\006\034\016\037\017" +
    "\001\002\000\014\031\154\034\uffe1\036\uffe1\040\uffe1\043" +
    "\uffe1\001\002\000\042\016\uffbd\017\uffbd\020\uffbd\021\uffbd" +
    "\022\uffbd\023\uffbd\024\uffbd\025\uffbd\026\uffbd\027\uffbd\031" +
    "\uffbd\032\uffbd\034\uffbd\036\uffbd\040\uffbd\043\uffbd\001\002" +
    "\000\004\035\150\001\002\000\032\005\uffe3\006\uffe3\010" +
    "\uffe3\012\uffe3\015\uffe3\030\uffe3\034\uffe3\035\uffe3\041\uffe3" +
    "\042\uffe3\044\uffe3\045\uffe3\001\002\000\016\031\uffd8\032" +
    "\146\034\uffd8\036\uffd8\040\uffd8\043\uffd8\001\002\000\042" +
    "\002\uffee\004\uffee\005\uffee\006\uffee\007\uffee\010\uffee\011" +
    "\uffee\012\uffee\015\uffee\030\uffee\034\uffee\035\uffee\041\uffee" +
    "\042\uffee\044\uffee\045\uffee\001\002\000\016\015\037\030" +
    "\053\034\143\035\050\044\051\045\052\001\002\000\032" +
    "\005\uffe8\006\uffe8\010\uffe8\012\uffe8\015\uffe8\030\uffe8\034" +
    "\uffe8\035\uffe8\041\uffe8\042\uffe8\044\uffe8\045\uffe8\001\002" +
    "\000\004\035\135\001\002\000\030\006\uffeb\010\uffeb\012" +
    "\uffeb\015\uffeb\030\uffeb\034\uffeb\035\uffeb\041\uffeb\042\uffeb" +
    "\044\uffeb\045\uffeb\001\002\000\014\015\037\030\053\035" +
    "\050\044\051\045\052\001\002\000\050\016\uffdb\017\uffdb" +
    "\020\uffdb\021\uffdb\022\uffdb\023\uffdb\024\uffdb\025\uffdb\026" +
    "\uffdb\027\uffdb\031\uffdb\032\uffdb\033\uffdb\034\uffdb\035\122" +
    "\036\uffdb\037\121\040\uffdb\043\uffdb\001\002\000\042\016" +
    "\uffbe\017\uffbe\020\uffbe\021\uffbe\022\uffbe\023\uffbe\024\uffbe" +
    "\025\uffbe\026\uffbe\027\uffbe\031\uffbe\032\uffbe\034\uffbe\036" +
    "\uffbe\040\uffbe\043\uffbe\001\002\000\014\015\037\030\053" +
    "\035\050\044\051\045\052\001\002\000\004\034\116\001" +
    "\002\000\032\005\uffe5\006\uffe5\010\uffe5\012\uffe5\015\uffe5" +
    "\030\uffe5\034\uffe5\035\uffe5\041\uffe5\042\uffe5\044\uffe5\045" +
    "\uffe5\001\002\000\042\016\uffc2\017\uffc2\020\uffc2\021\uffc2" +
    "\022\uffc2\023\uffc2\024\uffc2\025\uffc2\026\uffc2\027\uffc2\031" +
    "\uffc2\032\uffc2\034\uffc2\036\uffc2\040\uffc2\043\uffc2\001\002" +
    "\000\036\016\106\017\102\022\113\023\104\024\107\025" +
    "\103\026\110\027\105\031\uffcc\032\uffcc\034\uffcc\036\uffcc" +
    "\040\uffcc\043\uffcc\001\002\000\042\016\uffca\017\uffca\020" +
    "\075\021\074\022\uffca\023\uffca\024\uffca\025\uffca\026\uffca" +
    "\027\uffca\031\uffca\032\uffca\034\uffca\036\uffca\040\uffca\043" +
    "\uffca\001\002\000\016\031\uffce\032\uffce\034\uffce\036\uffce" +
    "\040\uffce\043\uffce\001\002\000\032\005\uffe9\006\uffe9\010" +
    "\uffe9\012\uffe9\015\uffe9\030\uffe9\034\uffe9\035\uffe9\041\uffe9" +
    "\042\uffe9\044\uffe9\045\uffe9\001\002\000\032\005\uffe7\006" +
    "\uffe7\010\uffe7\012\uffe7\015\uffe7\030\uffe7\034\uffe7\035\uffe7" +
    "\041\uffe7\042\uffe7\044\uffe7\045\uffe7\001\002\000\042\016" +
    "\uffc6\017\uffc6\020\uffc6\021\uffc6\022\uffc6\023\uffc6\024\uffc6" +
    "\025\uffc6\026\uffc6\027\uffc6\031\uffc6\032\uffc6\034\uffc6\036" +
    "\uffc6\040\uffc6\043\uffc6\001\002\000\032\005\uffe6\006\uffe6" +
    "\010\uffe6\012\uffe6\015\uffe6\030\uffe6\034\uffe6\035\uffe6\041" +
    "\uffe6\042\uffe6\044\uffe6\045\uffe6\001\002\000\042\016\uffbf" +
    "\017\uffbf\020\uffbf\021\uffbf\022\uffbf\023\uffbf\024\uffbf\025" +
    "\uffbf\026\uffbf\027\uffbf\031\uffbf\032\uffbf\034\uffbf\036\uffbf" +
    "\040\uffbf\043\uffbf\001\002\000\044\016\uffc0\017\uffc0\020" +
    "\uffc0\021\uffc0\022\uffc0\023\uffc0\024\uffc0\025\uffc0\026\uffc0" +
    "\027\uffc0\031\uffc0\032\uffc0\033\071\034\uffc0\036\uffc0\040" +
    "\uffc0\043\uffc0\001\002\000\016\031\uffd0\032\uffd0\034\uffd0" +
    "\036\uffd0\040\uffd0\043\uffd0\001\002\000\014\015\037\030" +
    "\053\035\050\044\051\045\052\001\002\000\012\034\uffe2" +
    "\036\uffe2\040\uffe2\043\uffe2\001\002\000\014\015\037\030" +
    "\077\035\050\044\051\045\052\001\002\000\014\015\uffc4" +
    "\030\uffc4\035\uffc4\044\uffc4\045\uffc4\001\002\000\014\015" +
    "\uffc5\030\uffc5\035\uffc5\044\uffc5\045\uffc5\001\002\000\042" +
    "\016\uffc7\017\uffc7\020\uffc7\021\uffc7\022\uffc7\023\uffc7\024" +
    "\uffc7\025\uffc7\026\uffc7\027\uffc7\031\uffc7\032\uffc7\034\uffc7" +
    "\036\uffc7\040\uffc7\043\uffc7\001\002\000\014\015\037\030" +
    "\077\035\050\044\051\045\052\001\002\000\042\016\uffc0" +
    "\017\uffc0\020\uffc0\021\uffc0\022\uffc0\023\uffc0\024\uffc0\025" +
    "\uffc0\026\uffc0\027\uffc0\031\uffc0\032\uffc0\034\uffc0\036\uffc0" +
    "\040\uffc0\043\uffc0\001\002\000\042\016\uffc3\017\uffc3\020" +
    "\uffc3\021\uffc3\022\uffc3\023\uffc3\024\uffc3\025\uffc3\026\uffc3" +
    "\027\uffc3\031\uffc3\032\uffc3\034\uffc3\036\uffc3\040\uffc3\043" +
    "\uffc3\001\002\000\014\015\uffc8\030\uffc8\035\uffc8\044\uffc8" +
    "\045\uffc8\001\002\000\014\015\uffd4\030\uffd4\035\uffd4\044" +
    "\uffd4\045\uffd4\001\002\000\014\015\uffd7\030\uffd7\035\uffd7" +
    "\044\uffd7\045\uffd7\001\002\000\014\015\uffd2\030\uffd2\035" +
    "\uffd2\044\uffd2\045\uffd2\001\002\000\014\015\uffc9\030\uffc9" +
    "\035\uffc9\044\uffc9\045\uffc9\001\002\000\014\015\uffd5\030" +
    "\uffd5\035\uffd5\044\uffd5\045\uffd5\001\002\000\014\015\uffd3" +
    "\030\uffd3\035\uffd3\044\uffd3\045\uffd3\001\002\000\014\015" +
    "\037\030\077\035\050\044\051\045\052\001\002\000\014" +
    "\015\037\030\077\035\050\044\051\045\052\001\002\000" +
    "\014\015\uffd6\030\uffd6\035\uffd6\044\uffd6\045\uffd6\001\002" +
    "\000\042\016\uffcb\017\uffcb\020\075\021\074\022\uffcb\023" +
    "\uffcb\024\uffcb\025\uffcb\026\uffcb\027\uffcb\031\uffcb\032\uffcb" +
    "\034\uffcb\036\uffcb\040\uffcb\043\uffcb\001\002\000\022\016" +
    "\106\017\102\031\uffcd\032\uffcd\034\uffcd\036\uffcd\040\uffcd" +
    "\043\uffcd\001\002\000\032\005\uffe4\006\uffe4\010\uffe4\012" +
    "\uffe4\015\uffe4\030\uffe4\034\uffe4\035\uffe4\041\uffe4\042\uffe4" +
    "\044\uffe4\045\uffe4\001\002\000\042\016\uffc6\017\uffc6\020" +
    "\uffc6\021\uffc6\022\uffc6\023\uffc6\024\uffc6\025\uffc6\026\uffc6" +
    "\027\uffc6\031\uffc6\032\uffc6\034\uffc6\036\uffc6\040\uffc6\043" +
    "\uffc6\001\002\000\016\031\uffcf\032\uffcf\034\uffcf\036\uffcf" +
    "\040\uffcf\043\uffcf\001\002\000\014\015\037\030\053\035" +
    "\050\044\051\045\052\001\002\000\016\015\037\030\053" +
    "\035\050\036\uffba\044\051\045\052\001\002\000\004\036" +
    "\130\001\002\000\006\036\uffb8\043\uffb8\001\002\000\006" +
    "\036\uffbb\043\126\001\002\000\014\015\037\030\053\035" +
    "\050\044\051\045\052\001\002\000\006\036\uffb9\043\uffb9" +
    "\001\002\000\042\016\uffbc\017\uffbc\020\uffbc\021\uffbc\022" +
    "\uffbc\023\uffbc\024\uffbc\025\uffbc\026\uffbc\027\uffbc\031\uffbc" +
    "\032\uffbc\034\uffbc\036\uffbc\040\uffbc\043\uffbc\001\002\000" +
    "\004\040\132\001\002\000\044\016\uffda\017\uffda\020\uffda" +
    "\021\uffda\022\uffda\023\uffda\024\uffda\025\uffda\026\uffda\027" +
    "\uffda\031\uffda\032\uffda\033\uffda\034\uffda\036\uffda\040\uffda" +
    "\043\uffda\001\002\000\004\036\134\001\002\000\042\016" +
    "\uffc1\017\uffc1\020\uffc1\021\uffc1\022\uffc1\023\uffc1\024\uffc1" +
    "\025\uffc1\026\uffc1\027\uffc1\031\uffc1\032\uffc1\034\uffc1\036" +
    "\uffc1\040\uffc1\043\uffc1\001\002\000\014\015\037\030\053" +
    "\035\050\044\051\045\052\001\002\000\004\036\137\001" +
    "\002\000\026\006\046\010\044\012\040\015\037\030\053" +
    "\034\041\035\050\041\030\044\051\045\052\001\002\000" +
    "\032\005\141\006\uffe0\010\uffe0\012\uffe0\015\uffe0\030\uffe0" +
    "\034\uffe0\035\uffe0\041\uffe0\042\uffe0\044\uffe0\045\uffe0\001" +
    "\002\000\026\006\046\010\044\012\040\015\037\030\053" +
    "\034\041\035\050\041\030\044\051\045\052\001\002\000" +
    "\032\005\uffdf\006\uffdf\010\uffdf\012\uffdf\015\uffdf\030\uffdf" +
    "\034\uffdf\035\uffdf\041\uffdf\042\uffdf\044\uffdf\045\uffdf\001" +
    "\002\000\032\005\uffdc\006\uffdc\010\uffdc\012\uffdc\015\uffdc" +
    "\030\uffdc\034\uffdc\035\uffdc\041\uffdc\042\uffdc\044\uffdc\045" +
    "\uffdc\001\002\000\004\034\145\001\002\000\032\005\uffdd" +
    "\006\uffdd\010\uffdd\012\uffdd\015\uffdd\030\uffdd\034\uffdd\035" +
    "\uffdd\041\uffdd\042\uffdd\044\uffdd\045\uffdd\001\002\000\014" +
    "\015\037\030\053\035\050\044\051\045\052\001\002\000" +
    "\016\031\uffd1\032\uffd1\034\uffd1\036\uffd1\040\uffd1\043\uffd1" +
    "\001\002\000\014\015\037\030\053\035\050\044\051\045" +
    "\052\001\002\000\004\036\152\001\002\000\026\006\046" +
    "\010\044\012\040\015\037\030\053\034\041\035\050\041" +
    "\030\044\051\045\052\001\002\000\032\005\uffde\006\uffde" +
    "\010\uffde\012\uffde\015\uffde\030\uffde\034\uffde\035\uffde\041" +
    "\uffde\042\uffde\044\uffde\045\uffde\001\002\000\014\015\037" +
    "\030\053\035\050\044\051\045\052\001\002\000\014\031" +
    "\154\034\uffd9\036\uffd9\040\uffd9\043\uffd9\001\002\000\010" +
    "\036\ufff0\037\157\043\ufff0\001\002\000\004\040\160\001" +
    "\002\000\006\036\uffef\043\uffef\001\002\000\010\004\005" +
    "\007\004\011\007\001\002\000\006\036\ufff2\043\ufff2\001" +
    "\002\000\004\040\164\001\002\000\004\034\165\001\002" +
    "\000\040\002\ufffa\004\ufffa\006\ufffa\007\ufffa\010\ufffa\011" +
    "\ufffa\012\ufffa\015\ufffa\030\ufffa\034\ufffa\035\ufffa\041\ufffa" +
    "\042\ufffa\044\ufffa\045\ufffa\001\002\000\012\002\uffff\004" +
    "\uffff\007\uffff\011\uffff\001\002\000\004\002\001\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\165\000\016\002\013\003\005\004\011\015\007\040" +
    "\012\043\010\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\002\013\003\165\004\011\040\012\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\031\024" +
    "\036\021\040\023\041\020\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\010\026\001\001\000\002\001\001\000" +
    "\004\042\030\001\001\000\010\002\032\037\031\040\033" +
    "\001\001\000\044\005\046\006\053\007\056\010\044\011" +
    "\061\012\062\013\064\014\054\016\035\017\041\020\060" +
    "\021\057\022\063\023\055\024\065\025\067\035\066\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\030" +
    "\006\143\007\056\016\035\017\041\020\060\021\057\022" +
    "\063\023\055\024\065\025\067\035\066\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\030\006" +
    "\132\007\056\016\035\017\041\020\060\021\057\022\063" +
    "\023\055\024\065\025\067\035\066\001\001\000\002\001" +
    "\001\000\002\001\001\000\022\007\056\020\060\021\057" +
    "\022\116\023\055\024\065\025\117\035\077\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\032\111\033\110\001\001\000\004\034\072\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\030\006\071\007\056\016\035" +
    "\017\041\020\060\021\057\022\063\023\055\024\065\025" +
    "\067\035\066\001\001\000\002\001\001\000\012\022\075" +
    "\023\055\024\065\035\077\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\022\100\023\055" +
    "\024\065\035\077\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\016\007\114\021\057\022\063\023\055" +
    "\024\065\035\077\001\001\000\014\021\113\022\063\023" +
    "\055\024\065\035\077\001\001\000\002\001\001\000\004" +
    "\034\072\001\001\000\004\032\111\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\030\006\130" +
    "\007\056\016\035\017\041\020\060\021\057\022\063\023" +
    "\055\024\065\025\067\035\066\001\001\000\034\006\123" +
    "\007\056\016\035\017\041\020\060\021\057\022\063\023" +
    "\055\024\065\025\067\026\122\027\124\035\066\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\030\006\126\007\056\016\035\017\041\020\060\021\057" +
    "\022\063\023\055\024\065\025\067\035\066\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\030\006" +
    "\135\007\056\016\035\017\041\020\060\021\057\022\063" +
    "\023\055\024\065\025\067\035\066\001\001\000\002\001" +
    "\001\000\044\005\137\006\053\007\056\010\044\011\061" +
    "\012\062\013\064\014\054\016\035\017\041\020\060\021" +
    "\057\022\063\023\055\024\065\025\067\035\066\001\001" +
    "\000\002\001\001\000\044\005\141\006\053\007\056\010" +
    "\044\011\061\012\062\013\064\014\054\016\035\017\041" +
    "\020\060\021\057\022\063\023\055\024\065\025\067\035" +
    "\066\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\022\007\056\020\060\021" +
    "\057\022\063\023\055\024\065\025\146\035\077\001\001" +
    "\000\002\001\001\000\030\006\150\007\056\016\035\017" +
    "\041\020\060\021\057\022\063\023\055\024\065\025\067" +
    "\035\066\001\001\000\002\001\001\000\044\005\152\006" +
    "\053\007\056\010\044\011\061\012\062\013\064\014\054" +
    "\016\035\017\041\020\060\021\057\022\063\023\055\024" +
    "\065\025\067\035\066\001\001\000\002\001\001\000\026" +
    "\007\056\016\154\017\041\020\060\021\057\022\063\023" +
    "\055\024\065\025\067\035\077\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\036\161\040\023\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    
    /* Change the method report_error so it will display the line and
       column of where the error occurred in the input as well as the
       reason for the error which is passed into the method in the
       String 'message'. */
    public void report_error(String message, Object info) {
   
        /* Create a StringBuffer called 'm' with the string 'Error' in it. */
        StringBuffer m = new StringBuffer("Error");
   
        /* Check if the information passed to the method is the same
           type as the type java_cup.runtime.Symbol. */
        if (info instanceof java_cup.runtime.Symbol) {
            /* Declare a java_cup.runtime.Symbol object 's' with the
               information in the object info that is being typecasted
               as a java_cup.runtime.Symbol object. */
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
   
            /* Check if the line number in the input is greater or
               equal to zero. */
            if (s.left >= 0) {                
                /* Add to the end of the StringBuffer error message
                   the line number of the error in the input. */
                m.append(" in line "+(s.left+1));   
                /* Check if the column number in the input is greater
                   or equal to zero. */
                if (s.right >= 0)                    
                    /* Add to the end of the StringBuffer error message
                       the column number of the error in the input. */
                    m.append(", column "+(s.right+1));
            }
        }
   
        /* Add to the end of the StringBuffer error message created in
           this method the message that was passed into this method. */
        m.append(" : "+message);
   
        /* Print the contents of the StringBuffer 'm', which contains
           an error message, out on a line. */
        System.err.println(m);
    }
   
    /* Change the method report_fatal_error so when it reports a fatal
       error it will display the line and column number of where the
       fatal error occurred in the input as well as the reason for the
       fatal error which is passed into the method in the object
       'message' and then exit.*/
    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        System.exit(1);
    }

    /* Assume true at the start, but set to false with parsing errors */
    public static boolean valid = true;



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		DecList start_val = (DecList)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= declaration_list 
            {
              DecList RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		DecList d = (DecList)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
               RESULT = d;
               
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // declaration_list ::= declaration_list declaration 
            {
              DecList RESULT =null;
		int dlleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int dlright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		DecList dl = (DecList)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Dec d = (Dec)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                           DecList t = dl;
                           while( t.tail != null ) {
                              t = t.tail;
                           }

                           t.tail = new DecList(d, null);
                           
                           RESULT = dl;
                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaration_list",33, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // declaration_list ::= declaration 
            {
              DecList RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Dec d = (Dec)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DecList(d, null); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaration_list",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // declaration ::= var_declaration 
            {
              Dec RESULT =null;
		int var_decleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int var_decright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Dec var_dec = (Dec)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                  RESULT = var_dec; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaration",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // declaration ::= fun_declaration 
            {
              Dec RESULT =null;
		int fun_decleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fun_decright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Dec fun_dec = (Dec)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = fun_dec; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaration",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // var_declaration ::= type_specifier ID SEMI 
            {
              Dec RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		NameTy t = (NameTy)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
                           System.out.println("Declaring " + i);
                           RESULT = new SimpleDec(tleft, tright, t, i); 
                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("var_declaration",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // var_declaration ::= type_specifier ID SQLPAREN NUM SQRPAREN SEMI 
            {
              Dec RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		NameTy t = (NameTy)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
                        IntExp array_size = new IntExp(ileft, iright, n); //get the size of the array 
                        RESULT = new ArrayDec(tleft, tright, t, i, array_size);
                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("var_declaration",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // type_specifier ::= INT 
            {
              NameTy RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                     RESULT = new NameTy(ileft, iright, NameTy.INT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type_specifier",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // type_specifier ::= VOID 
            {
              NameTy RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new NameTy(vleft, vright, NameTy.VOID); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type_specifier",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // type_specifier ::= BOOL 
            {
              NameTy RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new NameTy(bleft, bright, NameTy.BOOL); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type_specifier",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // fun_declaration ::= type_specifier ID LPAREN params RPAREN compound_stmt 
            {
              Dec RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		NameTy type = (NameTy)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object body = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                        RESULT = new FunctionDec(typeleft, typeright, type, name, (VarDecList)p, (CompoundExp)body);
                     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("fun_declaration",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // fun_prototype ::= type_specifier ID LPAREN params RPAREN SEMI 
            {
              Dec RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("fun_prototype",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // params ::= param_list 
            {
              Object RESULT =null;
		int p_listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int p_listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		VarDecList p_list = (VarDecList)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                  RESULT = p_list;
               
              CUP$parser$result = parser.getSymbolFactory().newSymbol("params",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // params ::= VOID 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("params",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // param_list ::= param_list COMMA param 
            {
              VarDecList RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		VarDecList l = (VarDecList)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                  VarDecList dcls = (VarDecList)l;
                  while(dcls.tail != null) {
                     dcls = dcls.tail;
                  }
                  dcls.tail = new VarDecList((VarDec)p, null);    // add to the list of parameters in the function definition
                  RESULT = l;
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("param_list",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // param_list ::= param 
            {
              VarDecList RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new VarDecList((VarDec)p, null); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("param_list",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // param ::= type_specifier ID 
            {
              Object RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NameTy type = (NameTy)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                RESULT = new SimpleDec(typeleft, typeright, type, name); // single variable parameter
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("param",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // param ::= type_specifier ID SQLPAREN SQRPAREN 
            {
              Object RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		NameTy type = (NameTy)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
                  RESULT = new ArrayDec(typeleft, typeright, type, name, null); // array parameter
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("param",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // compound_stmt ::= LCURLY local_declarations statem_list RCURLY 
            {
              Object RESULT =null;
		int ldecleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int ldecright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		VarDecList ldec = (VarDecList)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int slleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int slright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object sl = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		   
                        RESULT = new CompoundExp(slleft, slright, ldec, (ExpList)sl);
                     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("compound_stmt",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // local_declarations ::= local_declarations var_declaration 
            {
              VarDecList RESULT =null;
		int ldecleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int ldecright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		VarDecList ldec = (VarDecList)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int var_decleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int var_decright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Dec var_dec = (Dec)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                           RESULT = new VarDecList((VarDec)var_dec, ldec);     // variable declarations in the local function scope
                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("local_declarations",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // local_declarations ::= 
            {
              VarDecList RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("local_declarations",32, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // statem_list ::= statem_list statem 
            {
              Object RESULT =null;
		int st_listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int st_listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object st_list = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int stleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int stright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp st = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                     RESULT = new ExpList(st, (ExpList)st_list); // list of expressions in the function
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statem_list",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // statem_list ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("statem_list",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // statem ::= expression_stmt 
            {
              Exp RESULT =null;
		int e_stmleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e_stmright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e_stm = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                  RESULT = (Exp)e_stm;
               
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statem",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // statem ::= compound_stmt 
            {
              Exp RESULT =null;
		int c_stmleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int c_stmright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object c_stm = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                  RESULT = (Exp)c_stm;
              
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statem",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // statem ::= selection_stmt 
            {
              Exp RESULT =null;
		int s_stmleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int s_stmright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object s_stm = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                  RESULT = (Exp)s_stm;
              
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statem",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // statem ::= iteration_stmt 
            {
              Exp RESULT =null;
		int i_stmleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int i_stmright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object i_stm = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                  RESULT = (Exp)i_stm;
              
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statem",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // statem ::= return_stmt 
            {
              Exp RESULT =null;
		int r_stmleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int r_stmright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object r_stm = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                  RESULT = (Exp)r_stm;
              
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statem",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expression_stmt ::= expression SEMI 
            {
              Object RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Exp ex = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                        RESULT = ex;
                     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expression_stmt",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expression_stmt ::= SEMI 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expression_stmt",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expression ::= var EQ expression 
            {
              Exp RESULT =null;
		int vrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int vrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object vr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp ex = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                           VarExp left_side = new VarExp(vrleft, vrright, (Var)vr); 

                           RESULT = new AssignExp(vrleft, vrright, left_side, ex); // assign a variable
                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expression ::= obool_expression 
            {
              Exp RESULT =null;
		int oexleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int oexright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp oex = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                           
                           RESULT = oex;
                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expression",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // selection_stmt ::= IF LPAREN expression RPAREN statem 
            {
              Object RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Exp ex = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int stleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int stright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp st = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                     RESULT = new IfExp(exleft, exright, ex, st, null); 
                     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("selection_stmt",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // selection_stmt ::= IF LPAREN expression RPAREN statem ELSE statem 
            {
              Object RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Exp ex = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int st1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int st1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Exp st1 = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int st2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int st2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp st2 = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                     RESULT = new IfExp(exleft, exright, ex, st1, st2); 
                     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("selection_stmt",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // iteration_stmt ::= WHILE LPAREN expression RPAREN statem 
            {
              Object RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Exp ex = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int stleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int stright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp st = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                           RESULT = new WhileExp(exleft, exright, ex, st);
                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("iteration_stmt",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // return_stmt ::= RETURN expression SEMI 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("return_stmt",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // return_stmt ::= RETURN SEMI 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("return_stmt",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // var ::= ID 
            {
              Object RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                     RESULT = new SimpleVar(nameleft, nameright, name); //for single variable
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("var",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // var ::= ID SQLPAREN expression SQRPAREN 
            {
              Object RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Exp ex = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                     RESULT = new IndexVar(nameleft, nameright, name, ex); //for array variable
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("var",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // obool_expression ::= obool_expression LOR obool_expression 
            {
              Exp RESULT =null;
		int oex1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int oex1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Exp oex1 = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int oex2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int oex2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp oex2 = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                           RESULT = new OpExp(oex1left, oex1right, oex1, OpExp.LOR, oex2);
                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("obool_expression",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // obool_expression ::= abool_expression 
            {
              Exp RESULT =null;
		int aexleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aexright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp aex = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                           RESULT = aex;
                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("obool_expression",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // relop ::= LTE 
            {
              Integer RESULT =null;
		
                     RESULT = OpExp.LTE;
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("relop",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // relop ::= LT 
            {
              Integer RESULT =null;
		
                     RESULT = OpExp.LT;
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("relop",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // relop ::= GT 
            {
              Integer RESULT =null;
		
                     RESULT = OpExp.GT;
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("relop",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // relop ::= GTE 
            {
              Integer RESULT =null;
		
                     RESULT = OpExp.GTE;
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("relop",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // relop ::= ASSIGN 
            {
              Integer RESULT =null;
		
                     RESULT = OpExp.ASSIGN;
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("relop",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // relop ::= NEQ 
            {
              Integer RESULT =null;
		
                     RESULT = OpExp.NEQ;
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("relop",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // abool_expression ::= abool_expression LAND ubool_expression 
            {
              Exp RESULT =null;
		int aexleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aexright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Exp aex = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int uexleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int uexright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp uex = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                        RESULT = new OpExp(aexleft, aexright, aex, OpExp.LAND, uex);
                     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("abool_expression",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // abool_expression ::= ubool_expression 
            {
              Exp RESULT =null;
		int uexleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int uexright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp uex = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                        RESULT = (Exp)uex;
                     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("abool_expression",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // ubool_expression ::= UB ubool_expression 
            {
              Exp RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ubool_expression",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // ubool_expression ::= simple_expression 
            {
              Exp RESULT =null;
		int spexleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int spexright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp spex = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                           RESULT = spex;
                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ubool_expression",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // simple_expression ::= additive_expression relop additive_expression 
            {
              Exp RESULT =null;
		int adex1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int adex1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Exp adex1 = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rlleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int rlright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer rl = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int adex2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int adex2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp adex2 = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                           RESULT = new OpExp(adex1left, adex1right, adex1, rl, adex2);
                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_expression",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // simple_expression ::= additive_expression 
            {
              Exp RESULT =null;
		int adexleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int adexright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp adex = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                           RESULT = (Exp)adex;
                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("simple_expression",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // additive_expression ::= additive_expression addop term 
            {
              Exp RESULT =null;
		int adexleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int adexright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Exp adex = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int adpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int adpright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer adp = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int trmleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int trmright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp trm = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                           RESULT = new OpExp(adexleft, adexright, adex, adp, trm);
                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("additive_expression",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // additive_expression ::= term 
            {
              Exp RESULT =null;
		int trleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int trright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp tr = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                           RESULT = tr;
                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("additive_expression",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // addop ::= PLUS 
            {
              Integer RESULT =null;
		
                     RESULT = OpExp.PLUS;
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("addop",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // addop ::= MINUS 
            {
              Integer RESULT =null;
		
                     RESULT = OpExp.MINUS;
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("addop",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // term ::= term mulop signed_factor 
            {
              Exp RESULT =null;
		int trmleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int trmright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Exp trm = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int mlpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int mlpright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer mlp = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int sfleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sfright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp sf = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                     RESULT = new OpExp(trmleft, trmright, trm, mlp, sf);
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // term ::= signed_factor 
            {
              Exp RESULT =null;
		int sfleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sfright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp sf = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                     RESULT = sf;
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // mulop ::= TIMES 
            {
              Integer RESULT =null;
		
                     System.out.println("Times is running");
                     RESULT = OpExp.TIMES;
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("mulop",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // mulop ::= OVER 
            {
              Integer RESULT =null;
		
                     RESULT = OpExp.OVER;
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("mulop",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // signed_factor ::= UB signed_factor 
            {
              Exp RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("signed_factor",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // signed_factor ::= factor 
            {
              Exp RESULT =null;
		int fcleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fcright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp fc = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                        RESULT = fc;
                     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("signed_factor",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // factor ::= LPAREN expression RPAREN 
            {
              Exp RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Exp ex = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                        RESULT = ex;
                     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // factor ::= var 
            {
              Exp RESULT =null;
		int vrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vrright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object vr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                        RESULT = new VarExp(vrleft, vrright, (Var)vr);
                     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // factor ::= call 
            {
              Exp RESULT =null;
		int clleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int clright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp cl = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                     RESULT = cl;
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // factor ::= NUM 
            {
              Exp RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                        RESULT = new IntExp(nleft, nright, n);
                     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // factor ::= TRUTH 
            {
              Exp RESULT =null;
		
                        //
                     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // call ::= ID LPAREN args RPAREN 
            {
              Exp RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int asleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int asright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ExpList as = (ExpList)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                     RESULT = new CallExp(nameleft, nameright, name, as); //function call with 'as' as arguments.
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("call",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // args ::= arg_list 
            {
              ExpList RESULT =null;
		int alleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int alright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ExpList al = (ExpList)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                     RESULT = al;
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("args",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // args ::= 
            {
              ExpList RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("args",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // arg_list ::= arg_list COMMA expression 
            {
              ExpList RESULT =null;
		int alleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int alright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ExpList al = (ExpList)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp ex = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                     //ExpList tmp = al;
                     //while (tmp.tail != null) {
                     //   tmp = tmp.tail;
                     //}
                     ExpList tmp;
                     for (tmp = al; tmp.tail != null; tmp = tmp.tail);
                     tmp.tail = new ExpList(ex, null);
                     RESULT = al;

                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("arg_list",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // arg_list ::= expression 
            {
              ExpList RESULT =null;
		int exleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Exp ex = (Exp)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                     RESULT = new ExpList(ex, null);
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("arg_list",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
