
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 16;
  public static final int OVER = 14;
  public static final int LPAREN = 26;
  public static final int SEMI = 25;
  public static final int INT = 5;
  public static final int MINUS = 12;
  public static final int RPAREN = 27;
  public static final int LT = 15;
  public static final int BOOL = 2;
  public static final int COMMA = 32;
  public static final int NUM = 34;
  public static final int PLUS = 11;
  public static final int ASSIGN = 19;
  public static final int IF = 4;
  public static final int ID = 33;
  public static final int EOF = 0;
  public static final int LAND = 23;
  public static final int RETURN = 6;
  public static final int TRUE = 9;
  public static final int error = 1;
  public static final int LCURLY = 30;
  public static final int LOR = 22;
  public static final int UB = 21;
  public static final int NEQ = 20;
  public static final int VOID = 7;
  public static final int EQ = 24;
  public static final int ERROR = 36;
  public static final int GTE = 18;
  public static final int RCURLY = 31;
  public static final int TRUTH = 35;
  public static final int TIMES = 13;
  public static final int ELSE = 3;
  public static final int WHILE = 8;
  public static final int SQLPAREN = 28;
  public static final int FALSE = 10;
  public static final int GT = 17;
  public static final int SQRPAREN = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "ELSE",
  "IF",
  "INT",
  "RETURN",
  "VOID",
  "WHILE",
  "TRUE",
  "FALSE",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "LT",
  "LTE",
  "GT",
  "GTE",
  "ASSIGN",
  "NEQ",
  "UB",
  "LOR",
  "LAND",
  "EQ",
  "SEMI",
  "LPAREN",
  "RPAREN",
  "SQLPAREN",
  "SQRPAREN",
  "LCURLY",
  "RCURLY",
  "COMMA",
  "ID",
  "NUM",
  "TRUTH",
  "ERROR"
  };
}

